from utils.config import ConfigManager

TRANSLATIONS = {
    "en": {
        "title": "Ijtimai Qurbani Management System",
        "dashboard": "Dashboard",
        "participants": "Participants",
        "animals": "Animals",
        "allocation": "Allocation & Payments",
        "verify": "Verify Receipt",
        "distribution": "Distribution",
        "reports": "Reports",
        "total_participants": "Total Participants",
        "total_animals": "Total Animals",
        "shares_sold": "Shares Sold",
        "money_collected": "Money Collected",
        "pending_shares": "Pending Shares",
        "refresh_dashboard": "Refresh Dashboard",
        "add_participant": "Add Participant",
        "edit_selected": "Edit Selected",
        "delete_selected": "Delete Selected",
        "generate_receipt": "Generate Receipt",
        "search": "Search",
        "add_animal": "Add New Animal",
        "delete_animal": "Delete Animal",
        "allocate_share": "Allocate Share",
        "record_payment": "Record Payment",
        "verify_receipt": "Verify Receipt",
        "receipt_no": "Enter Receipt Number",
        "mark_delivered": "Mark Delivered / Undelivered",
        "refresh_list": "Refresh List",
        "export_participants": "Export Participants List (Excel)",
        "export_finance": "Export Financial Report (Excel)",
        "backup_db": "Backup Database",
        "restore_db": "Restore Database",
        "settings": "Settings",
        "language": "Language",
        "receipt_bg": "Receipt Background",
        "browse": "Browse",
        "save": "Save",
        "cancel": "Cancel",
        "success": "Success",
        "error": "Error",
        "warning": "Warning",
        "confirm_delete": "Are you sure you want to delete?",
        "valid_receipt": "✔ VALID RECEIPT",
        "invalid_receipt": "✘ INVALID / FAKE RECEIPT",
        "mosque_name": "Mosque Name",
        "set_bg": "Set Background",
        "remove_bg": "Remove Background",
        "change_password": "Change Admin Password",
        "current_password": "Current Password",
        "new_password": "New Password",
        "confirm_password": "Confirm New Password",
        "restart_required": "Please restart the application to apply language changes.",
        "id": "ID",
        "name": "Name",
        "phone": "Phone",
        "cnic": "CNIC",
        "shares": "Shares",
        "cost": "Total Cost",
        "paid": "Paid",
        "balance": "Balance",
        "type": "Type",
        "price": "Price",
        "seller": "Seller",
        "total": "Total Shares",
        "remaining": "Remaining",
        "status": "Status",
        "time": "Time",
        "delivered": "DELIVERED",
        "pending": "Pending",
        "english": "English",
        "urdu": "Urdu",
        "quick_register": "Quick Registration",
        "quick_register_header": "One-Click Registration & Receipt",
        "participant_info": "Participant Information",
        "allocation_payment": "Allocation & Payment",
        "select_animal": "Select Animal",
        "amount_paid": "Amount Paid",
        "register_print": "Register & Generate Receipt"
    },
    "ur": {
        "title": "اجتماعی قربانی مینجمنٹ سسٹم",
        "dashboard": "ڈیش بورڈ",
        "participants": "شرکاء",
        "animals": "جانور",
        "allocation": "حصص اور ادائیگی",
        "verify": "رسید کی تصدیق",
        "distribution": "تقسیم گوشت",
        "reports": "رپورٹس",
        "total_participants": "کل شرکاء",
        "total_animals": "کل جانور",
        "shares_sold": "فروخت شدہ حصص",
        "money_collected": "جمع شدہ رقم",
        "pending_shares": "بقیہ حصص",
        "refresh_dashboard": "تازہ کاری کریں",
        "add_participant": "شرکاء شامل کریں",
        "edit_selected": "تدوین کریں",
        "delete_selected": "حذف کریں",
        "generate_receipt": "رسید بنائیں",
        "search": "تلاش کریں",
        "add_animal": "نیا جانور شامل کریں",
        "delete_animal": "جانور حذف کریں",
        "allocate_share": "حصہ مختص کریں",
        "record_payment": "ادائیگی درج کریں",
        "verify_receipt": "رسید چیک کریں",
        "receipt_no": "رسید نمبر درج کریں",
        "mark_delivered": "ڈیلیوری کی حالت تبدیل کریں",
        "refresh_list": "لسٹ تازہ کریں",
        "export_participants": "شرکاء کی فہرست (ایکسل)",
        "export_finance": "مالیاتی رپورٹ (ایکسل)",
        "backup_db": "ڈیٹا بیک اپ",
        "restore_db": "ڈیٹا بحال کریں",
        "settings": "سیٹنگز",
        "language": "زبان",
        "receipt_bg": "رسید کا پس منظر",
        "browse": "منتخب کریں",
        "save": "محفوظ کریں",
        "cancel": "منسوخ کریں",
        "success": "کامیابی",
        "error": "غلطی",
        "warning": "انتباہ",
        "confirm_delete": "کیا آپ واقعی حذف کرنا چاہتے ہیں؟",
        "valid_receipt": "✔ درست رسید",
        "invalid_receipt": "✘ غلط / جعلی رسید",
        "mosque_name": "مسجد کا نام",
        "set_bg": "بیک گراؤنڈ سیٹ کریں",
        "remove_bg": "بیک گراؤنڈ ہٹائیں",
        "change_password": "پاس ورڈ تبدیل کریں",
        "current_password": "موجودہ پاس ورڈ",
        "new_password": "نیا پاس ورڈ",
        "confirm_password": "پاس ورڈ کی تصدیق کریں",
        "restart_required": "زبان کی تبدیلی کے لیے ایپ دوبارہ شروع کریں۔",
        "id": "شناخت",
        "name": "نام",
        "phone": "فون",
        "cnic": "شناختی کارڈ",
        "shares": "حصص",
        "cost": "کل قیمت",
        "paid": "ادا شدہ",
        "balance": "بقیہ",
        "type": "قسم",
        "price": "قیمت",
        "seller": "بیچنے والا",
        "total": "کل حصص",
        "remaining": "بقیہ",
        "status": "حالت",
        "time": "وقت",
        "delivered": "ڈیلیورڈ",
        "pending": "زیر التواء",
        "english": "انگریزی",
        "urdu": "اردو",
        "quick_register": "فوری رجسٹریشن",
        "quick_register_header": "ایک کلک رجسٹریشن اور رسید",
        "participant_info": "شریک کی معلومات",
        "allocation_payment": "حصص اور ادائیگی",
        "select_animal": "جانور منتخب کریں",
        "amount_paid": "ادا شدہ رقم",
        "register_print": "رجسٹر اور رسید بنائیں",
        "received_from": "وصول کنندہ:",
        "phone_label": "فون:",
        "cnic_label": "شناختی کارڈ:",
        "description": "تفصیل",
        "amount_pkr": "رقم (روپے)",
        "total_amount": "کل رقم",
        "receipt_footer": "یہ رسید کمپیوٹر سے تیار کی گئی ہے اور دستی دستخط کی ضرورت نہیں۔"
    }
}

class Localization:
    _lang = "en"

    @classmethod
    def set_language(cls, lang):
        if lang in TRANSLATIONS:
            cls._lang = lang
            ConfigManager.set("language", lang)

    @classmethod
    def get_language(cls):
        return ConfigManager.get("language", "en")

    @classmethod
    def t(cls, key):
        lang = cls.get_language()
        return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(key, key)